spring:
  config:
    import: env.properties
  profiles:
    active:
      - test
    group:
      local:
        - local-db
        - local-server
      test:
        - prod-db
        - local-server
      prod:
        - prod-db
        - prod-server
---
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
---
spring:
  config:
    activate:
      on-profile: local-server
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: prod-db
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${ORACLE_DB_URL}
    username: ${ORACLE_DB_USERNAME}
    password: ${ORACLE_DB_PASSWORD}
#  oracle:
#    net:
#      wallet_location: (SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=${TNS_ADMIN})))
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
